import type { Destination } from '../types'

export const DESTINATIONS: Destination[] = [
  {
    id: 'd-paris',
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    emoji: '',
    blurb: 'The city of light — art, gastronomy, and iconic architecture around every corner.',
    bestMonths: 'Apr – Jun, Sep – Oct',
    dailyBudgetUsd: 150,
    tags: ['romantic', 'art', 'food', 'history'],
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Montmartre', 'Le Marais'],
    photoUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&h=400&fit=crop',
  },
  {
    id: 'd-tokyo',
    name: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    emoji: '',
    blurb: 'A seamless blend of ultra-modern technology and centuries-old temples.',
    bestMonths: 'Mar – May, Sep – Nov',
    dailyBudgetUsd: 130,
    tags: ['culture', 'food', 'tech', 'temples'],
    highlights: ['Shibuya Crossing', 'Senso-ji Temple', 'Tsukiji Outer Market', 'Akihabara'],
    photoUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&h=400&fit=crop',
  },
  {
    id: 'd-nyc',
    name: 'New York City',
    country: 'USA',
    region: 'North America',
    emoji: '',
    blurb: 'The city that never sleeps — world-class dining, theater, and skyline views.',
    bestMonths: 'Apr – Jun, Sep – Nov',
    dailyBudgetUsd: 200,
    tags: ['urban', 'food', 'art', 'nightlife'],
    highlights: ['Central Park', 'Brooklyn Bridge', 'Times Square', 'The Met'],
    photoUrl: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600&h=400&fit=crop',
  },
  {
    id: 'd-bali',
    name: 'Bali',
    country: 'Indonesia',
    region: 'Asia',
    emoji: '',
    blurb: 'Tropical paradise with rice terraces, ancient temples, and vibrant surf culture.',
    bestMonths: 'Apr – Oct',
    dailyBudgetUsd: 60,
    tags: ['beach', 'nature', 'temples', 'budget'],
    highlights: ['Tegallalang Rice Terraces', 'Uluwatu Temple', 'Ubud', 'Seminyak Beach'],
    photoUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&h=400&fit=crop',
  },
  {
    id: 'd-rome',
    name: 'Rome',
    country: 'Italy',
    region: 'Europe',
    emoji: '',
    blurb: 'Walk through millennia of history — from the Colosseum to gelato on the piazza.',
    bestMonths: 'Apr – Jun, Sep – Oct',
    dailyBudgetUsd: 130,
    tags: ['history', 'food', 'art', 'romantic'],
    highlights: ['Colosseum', 'Vatican Museums', 'Trevi Fountain', 'Trastevere'],
    photoUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&h=400&fit=crop',
  },
  {
    id: 'd-sydney',
    name: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    emoji: '',
    blurb: 'Harbor city with stunning beaches, world-class dining, and a laid-back vibe.',
    bestMonths: 'Sep – Nov, Mar – May',
    dailyBudgetUsd: 160,
    tags: ['beach', 'urban', 'food', 'outdoors'],
    highlights: ['Opera House', 'Bondi Beach', 'Harbour Bridge', 'The Rocks'],
    photoUrl: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=600&h=400&fit=crop',
  },
  {
    id: 'd-cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    region: 'Africa',
    emoji: '',
    blurb: 'Mountains meet ocean — wine country, wildlife, and dramatic coastal scenery.',
    bestMonths: 'Nov – Mar',
    dailyBudgetUsd: 80,
    tags: ['nature', 'wine', 'outdoors', 'budget'],
    highlights: ['Table Mountain', 'Cape of Good Hope', 'V&A Waterfront', 'Stellenbosch'],
    photoUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=600&h=400&fit=crop',
  },
  {
    id: 'd-bangkok',
    name: 'Bangkok',
    country: 'Thailand',
    region: 'Asia',
    emoji: '',
    blurb: 'Chaotic, colorful, and delicious — temples, night markets, and rooftop bars.',
    bestMonths: 'Nov – Feb',
    dailyBudgetUsd: 45,
    tags: ['food', 'temples', 'nightlife', 'budget'],
    highlights: ['Grand Palace', 'Chatuchak Market', 'Wat Pho', 'Khao San Road'],
    photoUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600&h=400&fit=crop',
  },
  {
    id: 'd-iceland',
    name: 'Reykjavik',
    country: 'Iceland',
    region: 'Europe',
    emoji: '',
    blurb: 'Land of fire and ice — geysers, glaciers, and the Northern Lights.',
    bestMonths: 'Jun – Aug (midnight sun), Sep – Mar (northern lights)',
    dailyBudgetUsd: 200,
    tags: ['nature', 'adventure', 'outdoors', 'photography'],
    highlights: ['Blue Lagoon', 'Golden Circle', 'Northern Lights', 'Jokulsarlon'],
    photoUrl: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=600&h=400&fit=crop',
  },
  {
    id: 'd-dubai',
    name: 'Dubai',
    country: 'UAE',
    region: 'Middle East',
    emoji: '',
    blurb: 'Futuristic skyline, luxury shopping, and desert adventures.',
    bestMonths: 'Nov – Mar',
    dailyBudgetUsd: 180,
    tags: ['luxury', 'shopping', 'architecture', 'desert'],
    highlights: ['Burj Khalifa', 'Dubai Mall', 'Desert Safari', 'Palm Jumeirah'],
    photoUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&h=400&fit=crop',
  },
  {
    id: 'd-mexico-city',
    name: 'Mexico City',
    country: 'Mexico',
    region: 'North America',
    emoji: '',
    blurb: 'A vibrant capital — extraordinary food, murals, museums, and mezcal bars.',
    bestMonths: 'Mar – May, Oct – Nov',
    dailyBudgetUsd: 65,
    tags: ['food', 'art', 'culture', 'budget'],
    highlights: ['Zocalo', 'Frida Kahlo Museum', 'Chapultepec', 'Roma Norte'],
    photoUrl: 'https://images.unsplash.com/photo-1585464231875-d9ef1f5ad396?w=600&h=400&fit=crop',
  },
  {
    id: 'd-london',
    name: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    emoji: '',
    blurb: 'Royal palaces, world-class museums, and a legendary pub scene.',
    bestMonths: 'May – Sep',
    dailyBudgetUsd: 170,
    tags: ['history', 'art', 'food', 'urban'],
    highlights: ['Tower of London', 'British Museum', 'Borough Market', 'Shoreditch'],
    photoUrl: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=600&h=400&fit=crop',
  },
  {
    id: 'd-santorini',
    name: 'Santorini',
    country: 'Greece',
    region: 'Europe',
    emoji: '',
    blurb: 'Iconic white-washed villages perched on volcanic cliffs above the deep blue Aegean Sea.',
    bestMonths: 'May – Oct',
    dailyBudgetUsd: 140,
    tags: ['romantic', 'beach', 'photography', 'food'],
    highlights: ['Oia Sunset', 'Red Beach', 'Fira', 'Akrotiri Ruins'],
    photoUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=600&h=400&fit=crop',
  },
  {
    id: 'd-barcelona',
    name: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    emoji: '',
    blurb: 'Gaudi masterpieces, Mediterranean beaches, and endless tapas — a city that has it all.',
    bestMonths: 'May – Jun, Sep – Oct',
    dailyBudgetUsd: 120,
    tags: ['art', 'beach', 'food', 'architecture'],
    highlights: ['Sagrada Familia', 'Park Guell', 'La Rambla', 'Gothic Quarter'],
    photoUrl: 'https://images.unsplash.com/photo-1583422409516-2895a77efed6?w=600&h=400&fit=crop',
  },
  {
    id: 'd-grand-canyon',
    name: 'Grand Canyon',
    country: 'USA',
    region: 'North America',
    emoji: '',
    blurb: 'One of Earth\'s most awe-inspiring natural wonders — 277 miles of layered red rock.',
    bestMonths: 'Mar – May, Sep – Nov',
    dailyBudgetUsd: 100,
    tags: ['nature', 'adventure', 'hiking', 'outdoors'],
    highlights: ['South Rim', 'Bright Angel Trail', 'Skywalk', 'Havasu Falls'],
    photoUrl: 'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=600&h=400&fit=crop',
  },
  {
    id: 'd-banff',
    name: 'Banff',
    country: 'Canada',
    region: 'North America',
    emoji: '',
    blurb: 'Turquoise lakes, towering peaks, and pristine wilderness in the heart of the Canadian Rockies.',
    bestMonths: 'Jun – Sep (summer), Dec – Mar (skiing)',
    dailyBudgetUsd: 130,
    tags: ['nature', 'hiking', 'outdoors', 'adventure'],
    highlights: ['Lake Louise', 'Moraine Lake', 'Icefields Parkway', 'Banff Gondola'],
    photoUrl: 'https://images.unsplash.com/photo-1503614472-8c93d56e92ce?w=600&h=400&fit=crop',
  },
  {
    id: 'd-chichen-itza',
    name: 'Chichen Itza',
    country: 'Mexico',
    region: 'North America',
    emoji: '',
    blurb: 'Ancient Mayan ruins and one of the New Seven Wonders of the World, deep in the Yucatan jungle.',
    bestMonths: 'Nov – Mar',
    dailyBudgetUsd: 55,
    tags: ['history', 'culture', 'adventure', 'budget'],
    highlights: ['El Castillo Pyramid', 'Cenote Sagrado', 'Temple of Warriors', 'Ball Court'],
    photoUrl: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?w=600&h=400&fit=crop',
  },
  {
    id: 'd-rio',
    name: 'Rio de Janeiro',
    country: 'Brazil',
    region: 'South America',
    emoji: '',
    blurb: 'Dramatic mountains, golden beaches, and infectious energy — the marvelous city lives up to its name.',
    bestMonths: 'Dec – Mar (summer), Jun – Aug (mild)',
    dailyBudgetUsd: 80,
    tags: ['beach', 'culture', 'nightlife', 'nature'],
    highlights: ['Christ the Redeemer', 'Sugarloaf Mountain', 'Copacabana Beach', 'Lapa Arches'],
    photoUrl: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=600&h=400&fit=crop',
  },
  {
    id: 'd-machu-picchu',
    name: 'Machu Picchu',
    country: 'Peru',
    region: 'South America',
    emoji: '',
    blurb: 'The lost city of the Incas — a breathtaking ancient citadel perched high in the Andes.',
    bestMonths: 'Apr – Oct (dry season)',
    dailyBudgetUsd: 70,
    tags: ['history', 'hiking', 'adventure', 'culture'],
    highlights: ['Sun Gate', 'Inca Trail', 'Huayna Picchu', 'Temple of the Sun'],
    photoUrl: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=600&h=400&fit=crop',
  },
  {
    id: 'd-great-wall',
    name: 'Great Wall of China',
    country: 'China',
    region: 'Asia',
    emoji: '',
    blurb: 'Walk along one of humanity\'s greatest achievements — 13,000 miles of ancient fortification winding through mountains.',
    bestMonths: 'Apr – May, Sep – Oct',
    dailyBudgetUsd: 60,
    tags: ['history', 'hiking', 'culture', 'adventure'],
    highlights: ['Mutianyu Section', 'Jinshanling', 'Badaling', 'Simatai Night Tour'],
    photoUrl: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=600&h=400&fit=crop',
  },
  {
    id: 'd-mount-fuji',
    name: 'Mount Fuji',
    country: 'Japan',
    region: 'Asia',
    emoji: '',
    blurb: 'Japan\'s sacred peak — a perfectly symmetrical volcano surrounded by lakes, shrines, and hot springs.',
    bestMonths: 'Jul – Aug (climbing), Apr – May (viewing)',
    dailyBudgetUsd: 100,
    tags: ['nature', 'hiking', 'adventure', 'photography'],
    highlights: ['Summit Sunrise', 'Lake Kawaguchi', 'Chureito Pagoda', 'Hakone Hot Springs'],
    photoUrl: 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=600&h=400&fit=crop',
  },
  {
    id: 'd-taj-mahal',
    name: 'Taj Mahal',
    country: 'India',
    region: 'Asia',
    emoji: '',
    blurb: 'A monument to eternal love — white marble perfection at sunrise is an unforgettable sight.',
    bestMonths: 'Oct – Mar',
    dailyBudgetUsd: 40,
    tags: ['history', 'culture', 'architecture', 'budget'],
    highlights: ['Taj Mahal at Sunrise', 'Agra Fort', 'Mehtab Bagh', 'Fatehpur Sikri'],
    photoUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&h=400&fit=crop',
  },
  {
    id: 'd-singapore',
    name: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    emoji: '',
    blurb: 'A futuristic city-state where stunning architecture, world-class food, and lush gardens converge.',
    bestMonths: 'Feb – Apr',
    dailyBudgetUsd: 150,
    tags: ['food', 'urban', 'architecture', 'shopping'],
    highlights: ['Marina Bay Sands', 'Gardens by the Bay', 'Hawker Centers', 'Sentosa Island'],
    photoUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=600&h=400&fit=crop',
  },
  {
    id: 'd-ha-long-bay',
    name: 'Ha Long Bay',
    country: 'Vietnam',
    region: 'Asia',
    emoji: '',
    blurb: 'Thousands of limestone karsts rising from emerald waters — a UNESCO wonder best explored by boat.',
    bestMonths: 'Oct – Dec, Mar – May',
    dailyBudgetUsd: 45,
    tags: ['nature', 'adventure', 'photography', 'budget'],
    highlights: ['Overnight Cruise', 'Sung Sot Cave', 'Kayaking', 'Ti Top Island'],
    photoUrl: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=600&h=400&fit=crop',
  },
  {
    id: 'd-pyramids-giza',
    name: 'Pyramids of Giza',
    country: 'Egypt',
    region: 'Africa',
    emoji: '',
    blurb: 'The last surviving Wonder of the Ancient World — 4,500 years old and still utterly magnificent.',
    bestMonths: 'Oct – Apr',
    dailyBudgetUsd: 50,
    tags: ['history', 'culture', 'adventure', 'photography'],
    highlights: ['Great Pyramid', 'The Sphinx', 'Sound & Light Show', 'Saqqara'],
    photoUrl: 'https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=600&h=400&fit=crop',
  },
  {
    id: 'd-serengeti',
    name: 'Serengeti',
    country: 'Tanzania',
    region: 'Africa',
    emoji: '',
    blurb: 'Witness the greatest wildlife migration on Earth across vast golden plains.',
    bestMonths: 'Jun – Oct (migration), Jan – Feb (calving)',
    dailyBudgetUsd: 250,
    tags: ['nature', 'wildlife', 'adventure', 'photography'],
    highlights: ['Great Migration', 'Big Five Safari', 'Ngorongoro Crater', 'Balloon Safari'],
    photoUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=600&h=400&fit=crop',
  },
]

export const EXPLORE_EXTRA: Destination[] = [
  {
    id: 'd-amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    region: 'Europe',
    emoji: '',
    blurb: 'Canal-laced charm with world-class museums, cycling culture, and vibrant nightlife.',
    bestMonths: 'Apr – Sep',
    dailyBudgetUsd: 140,
    tags: ['art', 'culture', 'nightlife', 'cycling'],
    highlights: ['Rijksmuseum', 'Anne Frank House', 'Vondelpark', 'Jordaan'],
    photoUrl: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=600&h=400&fit=crop',
  },
  {
    id: 'd-prague',
    name: 'Prague',
    country: 'Czech Republic',
    region: 'Europe',
    emoji: '',
    blurb: 'A fairy-tale city of Gothic spires, cobblestone lanes, and legendary beer halls.',
    bestMonths: 'Apr – Jun, Sep – Oct',
    dailyBudgetUsd: 70,
    tags: ['history', 'architecture', 'budget', 'nightlife'],
    highlights: ['Charles Bridge', 'Prague Castle', 'Old Town Square', 'Astronomical Clock'],
    photoUrl: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=600&h=400&fit=crop',
  },
  {
    id: 'd-vienna',
    name: 'Vienna',
    country: 'Austria',
    region: 'Europe',
    emoji: '',
    blurb: 'Imperial grandeur meets coffeehouse culture — classical music, palaces, and Sachertorte.',
    bestMonths: 'Apr – Jun, Sep – Oct',
    dailyBudgetUsd: 130,
    tags: ['history', 'art', 'food', 'architecture'],
    highlights: ['Schonbrunn Palace', 'St. Stephens Cathedral', 'Belvedere', 'Naschmarkt'],
    photoUrl: 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=600&h=400&fit=crop',
  },
  {
    id: 'd-lisbon',
    name: 'Lisbon',
    country: 'Portugal',
    region: 'Europe',
    emoji: '',
    blurb: 'Sun-drenched hills, pastel-tiled facades, and legendary custard tarts by the river.',
    bestMonths: 'Mar – Oct',
    dailyBudgetUsd: 90,
    tags: ['food', 'culture', 'history', 'nightlife'],
    highlights: ['Belem Tower', 'Alfama District', 'Time Out Market', 'Tram 28'],
    photoUrl: 'https://images.unsplash.com/photo-1548707309-dcebeab426c8?w=600&h=400&fit=crop',
  },
  {
    id: 'd-athens',
    name: 'Athens',
    country: 'Greece',
    region: 'Europe',
    emoji: '',
    blurb: 'The cradle of Western civilization — ancient ruins, lively tavernas, and Mediterranean warmth.',
    bestMonths: 'Apr – Jun, Sep – Nov',
    dailyBudgetUsd: 85,
    tags: ['history', 'food', 'culture', 'architecture'],
    highlights: ['Acropolis', 'Parthenon', 'Plaka', 'Temple of Olympian Zeus'],
    photoUrl: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=600&h=400&fit=crop',
  },
  {
    id: 'd-edinburgh',
    name: 'Edinburgh',
    country: 'United Kingdom',
    region: 'Europe',
    emoji: '',
    blurb: 'A dramatic hilltop castle, winding medieval streets, and world-famous festivals.',
    bestMonths: 'May – Sep',
    dailyBudgetUsd: 130,
    tags: ['history', 'culture', 'architecture', 'festivals'],
    highlights: ['Edinburgh Castle', 'Royal Mile', 'Arthur\'s Seat', 'Fringe Festival'],
    photoUrl: 'https://images.unsplash.com/photo-1506377585622-bedcbb027afc?w=600&h=400&fit=crop',
  },
  {
    id: 'd-budapest',
    name: 'Budapest',
    country: 'Hungary',
    region: 'Europe',
    emoji: '',
    blurb: 'Thermal baths, ruin bars, and stunning Danube views — one of Europe\'s best-value capitals.',
    bestMonths: 'Mar – May, Sep – Nov',
    dailyBudgetUsd: 65,
    tags: ['history', 'nightlife', 'budget', 'architecture'],
    highlights: ['Fisherman\'s Bastion', 'Szechenyi Baths', 'Ruin Bars', 'Parliament Building'],
    photoUrl: 'https://images.unsplash.com/photo-1551867633-194f125bddfa?w=600&h=400&fit=crop',
  },
  {
    id: 'd-dubrovnik',
    name: 'Dubrovnik',
    country: 'Croatia',
    region: 'Europe',
    emoji: '',
    blurb: 'The Pearl of the Adriatic — terracotta rooftops, ancient walls, and crystal-clear waters.',
    bestMonths: 'May – Jun, Sep – Oct',
    dailyBudgetUsd: 110,
    tags: ['history', 'beach', 'architecture', 'photography'],
    highlights: ['City Walls Walk', 'Old Town', 'Lokrum Island', 'Cable Car'],
    photoUrl: 'https://images.unsplash.com/photo-1555990538-1e15a2d8a4c8?w=600&h=400&fit=crop',
  },
  {
    id: 'd-florence',
    name: 'Florence',
    country: 'Italy',
    region: 'Europe',
    emoji: '',
    blurb: 'Renaissance art capital — Michelangelo, Botticelli, and the best gelato in Italy.',
    bestMonths: 'Apr – Jun, Sep – Oct',
    dailyBudgetUsd: 120,
    tags: ['art', 'food', 'history', 'architecture'],
    highlights: ['Uffizi Gallery', 'Duomo', 'Ponte Vecchio', 'Piazzale Michelangelo'],
    photoUrl: 'https://images.unsplash.com/photo-1543429776-2782f8f79ae7?w=600&h=400&fit=crop',
  },
  {
    id: 'd-venice',
    name: 'Venice',
    country: 'Italy',
    region: 'Europe',
    emoji: '',
    blurb: 'A floating city of gondolas, bridges, and timeless romance on the Adriatic lagoon.',
    bestMonths: 'Apr – Jun, Sep – Nov',
    dailyBudgetUsd: 150,
    tags: ['romantic', 'architecture', 'history', 'art'],
    highlights: ['St. Mark\'s Basilica', 'Grand Canal', 'Rialto Bridge', 'Burano Island'],
    photoUrl: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=600&h=400&fit=crop',
  },
  {
    id: 'd-zurich',
    name: 'Zurich',
    country: 'Switzerland',
    region: 'Europe',
    emoji: '',
    blurb: 'Pristine lakes, Alpine views, and a polished city blending old-world charm with modern luxury.',
    bestMonths: 'Jun – Sep',
    dailyBudgetUsd: 200,
    tags: ['nature', 'luxury', 'outdoors', 'food'],
    highlights: ['Lake Zurich', 'Bahnhofstrasse', 'Old Town', 'Uetliberg Mountain'],
    photoUrl: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=600&h=400&fit=crop',
  },
  {
    id: 'd-copenhagen',
    name: 'Copenhagen',
    country: 'Denmark',
    region: 'Europe',
    emoji: '',
    blurb: 'Hygge capital of the world — colorful harbors, innovative food, and effortless Scandinavian cool.',
    bestMonths: 'May – Sep',
    dailyBudgetUsd: 160,
    tags: ['food', 'culture', 'cycling', 'architecture'],
    highlights: ['Nyhavn', 'Tivoli Gardens', 'Little Mermaid', 'Christiania'],
    photoUrl: 'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=600&h=400&fit=crop',
  },
  {
    id: 'd-amalfi',
    name: 'Amalfi Coast',
    country: 'Italy',
    region: 'Europe',
    emoji: '',
    blurb: 'Dramatic cliffside villages cascading down to turquoise Mediterranean waters.',
    bestMonths: 'May – Sep',
    dailyBudgetUsd: 140,
    tags: ['romantic', 'beach', 'food', 'photography'],
    highlights: ['Positano', 'Ravello', 'Path of the Gods', 'Capri Day Trip'],
    photoUrl: 'https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=600&h=400&fit=crop',
  },
  {
    id: 'd-munich',
    name: 'Munich',
    country: 'Germany',
    region: 'Europe',
    emoji: '',
    blurb: 'Bavarian capital of beer gardens, lederhosen, and Alpine day trips.',
    bestMonths: 'May – Oct',
    dailyBudgetUsd: 120,
    tags: ['food', 'culture', 'history', 'outdoors'],
    highlights: ['Marienplatz', 'Englischer Garten', 'Neuschwanstein Castle', 'Oktoberfest'],
    photoUrl: 'https://images.unsplash.com/photo-1595867818082-083862f3d630?w=600&h=400&fit=crop',
  },
  {
    id: 'd-istanbul',
    name: 'Istanbul',
    country: 'Turkey',
    region: 'Europe',
    emoji: '',
    blurb: 'Where East meets West — Byzantine mosaics, Ottoman mosques, and bustling bazaars.',
    bestMonths: 'Apr – May, Sep – Nov',
    dailyBudgetUsd: 70,
    tags: ['history', 'food', 'culture', 'shopping'],
    highlights: ['Hagia Sophia', 'Blue Mosque', 'Grand Bazaar', 'Bosphorus Cruise'],
    photoUrl: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=600&h=400&fit=crop',
  },
  {
    id: 'd-kyoto',
    name: 'Kyoto',
    country: 'Japan',
    region: 'Asia',
    emoji: '',
    blurb: 'Japan\'s cultural heart — thousands of temples, bamboo groves, and geisha districts.',
    bestMonths: 'Mar – May, Oct – Nov',
    dailyBudgetUsd: 110,
    tags: ['temples', 'culture', 'nature', 'food'],
    highlights: ['Fushimi Inari Shrine', 'Arashiyama Bamboo Grove', 'Kinkaku-ji', 'Gion District'],
    photoUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&h=400&fit=crop',
  },
  {
    id: 'd-seoul',
    name: 'Seoul',
    country: 'South Korea',
    region: 'Asia',
    emoji: '',
    blurb: 'K-pop, palaces, and sizzling street food — a dazzling blend of ancient and ultra-modern.',
    bestMonths: 'Mar – May, Sep – Nov',
    dailyBudgetUsd: 90,
    tags: ['food', 'culture', 'shopping', 'nightlife'],
    highlights: ['Gyeongbokgung Palace', 'Bukchon Hanok Village', 'Myeongdong', 'Namsan Tower'],
    photoUrl: 'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=600&h=400&fit=crop',
  },
  {
    id: 'd-hong-kong',
    name: 'Hong Kong',
    country: 'China',
    region: 'Asia',
    emoji: '',
    blurb: 'A neon-lit skyline, dim sum paradise, and hiking trails with harbor views.',
    bestMonths: 'Oct – Dec',
    dailyBudgetUsd: 130,
    tags: ['food', 'urban', 'shopping', 'nightlife'],
    highlights: ['Victoria Peak', 'Star Ferry', 'Temple Street Night Market', 'Lantau Island'],
    photoUrl: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=600&h=400&fit=crop',
  },
  {
    id: 'd-maldives',
    name: 'Maldives',
    country: 'Maldives',
    region: 'Asia',
    emoji: '',
    blurb: 'Overwater villas, turquoise lagoons, and some of the best diving on the planet.',
    bestMonths: 'Nov – Apr',
    dailyBudgetUsd: 300,
    tags: ['beach', 'luxury', 'romantic', 'diving'],
    highlights: ['Overwater Bungalows', 'Snorkeling with Mantas', 'Bioluminescent Beach', 'Spa Retreats'],
    photoUrl: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=600&h=400&fit=crop',
  },
  {
    id: 'd-phuket',
    name: 'Phuket',
    country: 'Thailand',
    region: 'Asia',
    emoji: '',
    blurb: 'Thailand\'s largest island — powdery beaches, turquoise coves, and lively nightlife.',
    bestMonths: 'Nov – Apr',
    dailyBudgetUsd: 50,
    tags: ['beach', 'nightlife', 'budget', 'food'],
    highlights: ['Phi Phi Islands', 'Patong Beach', 'Big Buddha', 'Old Phuket Town'],
    photoUrl: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=600&h=400&fit=crop',
  },
  {
    id: 'd-angkor-wat',
    name: 'Angkor Wat',
    country: 'Cambodia',
    region: 'Asia',
    emoji: '',
    blurb: 'The largest religious monument on Earth — ancient temple complexes swallowed by jungle.',
    bestMonths: 'Nov – Mar',
    dailyBudgetUsd: 40,
    tags: ['history', 'culture', 'temples', 'budget'],
    highlights: ['Angkor Wat Sunrise', 'Bayon Temple', 'Ta Prohm', 'Tonle Sap Lake'],
    photoUrl: 'https://images.unsplash.com/photo-1508159452718-d22f35e54ef3?w=600&h=400&fit=crop',
  },
  {
    id: 'd-kathmandu',
    name: 'Kathmandu',
    country: 'Nepal',
    region: 'Asia',
    emoji: '',
    blurb: 'Gateway to the Himalayas — ancient temples, prayer flags, and Everest trekking.',
    bestMonths: 'Oct – Nov, Mar – Apr',
    dailyBudgetUsd: 35,
    tags: ['adventure', 'hiking', 'culture', 'budget'],
    highlights: ['Boudhanath Stupa', 'Swayambhunath', 'Thamel', 'Everest Base Camp Trek'],
    photoUrl: 'https://images.unsplash.com/photo-1558799401-1dcba79834c2?w=600&h=400&fit=crop',
  },
  {
    id: 'd-jaipur',
    name: 'Jaipur',
    country: 'India',
    region: 'Asia',
    emoji: '',
    blurb: 'The Pink City — ornate palaces, vibrant bazaars, and Rajasthani hospitality.',
    bestMonths: 'Oct – Mar',
    dailyBudgetUsd: 35,
    tags: ['history', 'culture', 'shopping', 'budget'],
    highlights: ['Amber Fort', 'Hawa Mahal', 'City Palace', 'Jantar Mantar'],
    photoUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&h=400&fit=crop',
  },
  {
    id: 'd-shanghai',
    name: 'Shanghai',
    country: 'China',
    region: 'Asia',
    emoji: '',
    blurb: 'Futuristic skyline on the Bund, French Concession charm, and legendary soup dumplings.',
    bestMonths: 'Mar – May, Sep – Nov',
    dailyBudgetUsd: 80,
    tags: ['urban', 'food', 'architecture', 'shopping'],
    highlights: ['The Bund', 'Yu Garden', 'French Concession', 'Pudong Skyline'],
    photoUrl: 'https://images.unsplash.com/photo-1538428494232-9c0d8a3ab403?w=600&h=400&fit=crop',
  },
  {
    id: 'd-petra',
    name: 'Petra',
    country: 'Jordan',
    region: 'Middle East',
    emoji: '',
    blurb: 'A rose-red city carved into sandstone cliffs — one of the New Seven Wonders of the World.',
    bestMonths: 'Mar – May, Sep – Nov',
    dailyBudgetUsd: 80,
    tags: ['history', 'adventure', 'architecture', 'photography'],
    highlights: ['The Treasury', 'The Monastery', 'Siq Canyon', 'Petra by Night'],
    photoUrl: 'https://images.unsplash.com/photo-1579606032821-4e6161c81571?w=600&h=400&fit=crop',
  },
  {
    id: 'd-jerusalem',
    name: 'Jerusalem',
    country: 'Israel',
    region: 'Middle East',
    emoji: '',
    blurb: 'Sacred to three faiths — ancient walls, golden domes, and millennia of living history.',
    bestMonths: 'Mar – May, Sep – Nov',
    dailyBudgetUsd: 120,
    tags: ['history', 'culture', 'religion', 'food'],
    highlights: ['Western Wall', 'Dome of the Rock', 'Church of the Holy Sepulchre', 'Old City'],
    photoUrl: 'https://images.unsplash.com/photo-1547483238-2cbf881a559f?w=600&h=400&fit=crop',
  },
  {
    id: 'd-los-angeles',
    name: 'Los Angeles',
    country: 'USA',
    region: 'North America',
    emoji: '',
    blurb: 'Hollywood glamour, beach boardwalks, and taco trucks under endless sunshine.',
    bestMonths: 'Mar – May, Sep – Nov',
    dailyBudgetUsd: 170,
    tags: ['beach', 'urban', 'food', 'entertainment'],
    highlights: ['Hollywood Sign', 'Santa Monica Pier', 'Griffith Observatory', 'Venice Beach'],
    photoUrl: 'https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?w=600&h=400&fit=crop',
  },
  {
    id: 'd-san-francisco',
    name: 'San Francisco',
    country: 'USA',
    region: 'North America',
    emoji: '',
    blurb: 'Foggy bridges, cable cars, and a legendary food scene on the Pacific coast.',
    bestMonths: 'Sep – Nov',
    dailyBudgetUsd: 190,
    tags: ['food', 'urban', 'culture', 'outdoors'],
    highlights: ['Golden Gate Bridge', 'Fisherman\'s Wharf', 'Alcatraz Island', 'Chinatown'],
    photoUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=600&h=400&fit=crop',
  },
  {
    id: 'd-las-vegas',
    name: 'Las Vegas',
    country: 'USA',
    region: 'North America',
    emoji: '',
    blurb: 'Neon-lit entertainment capital — world-class shows, dining, and desert adventures.',
    bestMonths: 'Mar – May, Sep – Nov',
    dailyBudgetUsd: 150,
    tags: ['nightlife', 'entertainment', 'food', 'shopping'],
    highlights: ['The Strip', 'Fremont Street', 'Red Rock Canyon', 'Shows & Concerts'],
    photoUrl: 'https://images.unsplash.com/photo-1605833556294-ea5c7a74f57d?w=600&h=400&fit=crop',
  },
  {
    id: 'd-miami',
    name: 'Miami',
    country: 'USA',
    region: 'North America',
    emoji: '',
    blurb: 'Art Deco, Latin beats, and turquoise waters — a tropical gateway city.',
    bestMonths: 'Nov – Apr',
    dailyBudgetUsd: 160,
    tags: ['beach', 'nightlife', 'food', 'art'],
    highlights: ['South Beach', 'Wynwood Walls', 'Little Havana', 'Art Deco District'],
    photoUrl: 'https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=600&h=400&fit=crop',
  },
  {
    id: 'd-hawaii',
    name: 'Honolulu',
    country: 'USA',
    region: 'North America',
    emoji: '',
    blurb: 'Aloha spirit, volcanic landscapes, and legendary surfing on Oahu\'s golden shores.',
    bestMonths: 'Apr – Jun, Sep – Nov',
    dailyBudgetUsd: 180,
    tags: ['beach', 'nature', 'outdoors', 'food'],
    highlights: ['Waikiki Beach', 'Diamond Head', 'Pearl Harbor', 'North Shore'],
    photoUrl: 'https://images.unsplash.com/photo-1507876466758-bc54f384809c?w=600&h=400&fit=crop',
  },
  {
    id: 'd-cancun',
    name: 'Cancun',
    country: 'Mexico',
    region: 'North America',
    emoji: '',
    blurb: 'Caribbean beaches, cenote swimming, and ancient Mayan ruins just a day trip away.',
    bestMonths: 'Dec – Apr',
    dailyBudgetUsd: 90,
    tags: ['beach', 'nightlife', 'adventure', 'food'],
    highlights: ['Hotel Zone Beaches', 'Isla Mujeres', 'Cenotes', 'Tulum Ruins'],
    photoUrl: 'https://images.unsplash.com/photo-1510097467424-192d713fd8b2?w=600&h=400&fit=crop',
  },
  {
    id: 'd-vancouver',
    name: 'Vancouver',
    country: 'Canada',
    region: 'North America',
    emoji: '',
    blurb: 'Mountains meet ocean — stunning nature, diverse cuisine, and laid-back West Coast vibes.',
    bestMonths: 'Jun – Sep',
    dailyBudgetUsd: 140,
    tags: ['nature', 'food', 'outdoors', 'urban'],
    highlights: ['Stanley Park', 'Granville Island', 'Capilano Bridge', 'Gastown'],
    photoUrl: 'https://images.unsplash.com/photo-1559511260-66a68e7e3765?w=600&h=400&fit=crop',
  },
  {
    id: 'd-washington-dc',
    name: 'Washington DC',
    country: 'USA',
    region: 'North America',
    emoji: '',
    blurb: 'The nation\'s capital — free museums, iconic monuments, and cherry blossom season.',
    bestMonths: 'Mar – May, Sep – Nov',
    dailyBudgetUsd: 150,
    tags: ['history', 'culture', 'art', 'urban'],
    highlights: ['National Mall', 'Smithsonian Museums', 'Lincoln Memorial', 'Georgetown'],
    photoUrl: 'https://images.unsplash.com/photo-1617581629397-a72507c3de9e?w=600&h=400&fit=crop',
  },
  {
    id: 'd-chicago',
    name: 'Chicago',
    country: 'USA',
    region: 'North America',
    emoji: '',
    blurb: 'Deep-dish pizza, bold architecture, and blues music on the shores of Lake Michigan.',
    bestMonths: 'May – Oct',
    dailyBudgetUsd: 150,
    tags: ['food', 'architecture', 'art', 'urban'],
    highlights: ['Millennium Park', 'Art Institute', 'Navy Pier', 'Architecture Boat Tour'],
    photoUrl: 'https://images.unsplash.com/photo-1494522855154-9297ac14b55f?w=600&h=400&fit=crop',
  },
  {
    id: 'd-new-orleans',
    name: 'New Orleans',
    country: 'USA',
    region: 'North America',
    emoji: '',
    blurb: 'Jazz, jambalaya, and joie de vivre — a city that celebrates life like no other.',
    bestMonths: 'Feb – May, Oct – Nov',
    dailyBudgetUsd: 130,
    tags: ['food', 'nightlife', 'culture', 'music'],
    highlights: ['French Quarter', 'Bourbon Street', 'Garden District', 'Mardi Gras'],
    photoUrl: 'https://images.unsplash.com/photo-1568402102990-bc541580b59f?w=600&h=400&fit=crop',
  },
  {
    id: 'd-yellowstone',
    name: 'Yellowstone',
    country: 'USA',
    region: 'North America',
    emoji: '',
    blurb: 'America\'s first national park — geysers, hot springs, and roaming bison.',
    bestMonths: 'May – Sep',
    dailyBudgetUsd: 100,
    tags: ['nature', 'wildlife', 'outdoors', 'adventure'],
    highlights: ['Old Faithful', 'Grand Prismatic Spring', 'Yellowstone Lake', 'Lamar Valley Wildlife'],
    photoUrl: 'https://images.unsplash.com/photo-1533953263968-874b080e8870?w=600&h=400&fit=crop',
  },
  {
    id: 'd-niagara-falls',
    name: 'Niagara Falls',
    country: 'USA / Canada',
    region: 'North America',
    emoji: '',
    blurb: 'One of the world\'s most powerful waterfalls — thundering cascades on the US-Canada border.',
    bestMonths: 'Jun – Aug',
    dailyBudgetUsd: 110,
    tags: ['nature', 'outdoors', 'photography', 'adventure'],
    highlights: ['Maid of the Mist', 'Horseshoe Falls', 'Journey Behind the Falls', 'Niagara Parkway'],
    photoUrl: 'https://images.unsplash.com/photo-1489447068241-b3490214e879?w=600&h=400&fit=crop',
  },
  {
    id: 'd-buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    region: 'South America',
    emoji: '',
    blurb: 'The Paris of South America — tango, steak, and passionate nightlife.',
    bestMonths: 'Mar – May, Sep – Nov',
    dailyBudgetUsd: 60,
    tags: ['food', 'culture', 'nightlife', 'art'],
    highlights: ['La Boca', 'Recoleta Cemetery', 'San Telmo Market', 'Tango Shows'],
    photoUrl: 'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=600&h=400&fit=crop',
  },
  {
    id: 'd-cartagena',
    name: 'Cartagena',
    country: 'Colombia',
    region: 'South America',
    emoji: '',
    blurb: 'Colorful colonial walls, Caribbean breezes, and vibrant plazas full of music.',
    bestMonths: 'Dec – Apr',
    dailyBudgetUsd: 60,
    tags: ['history', 'beach', 'culture', 'food'],
    highlights: ['Old Walled City', 'Rosario Islands', 'Castillo San Felipe', 'Getsemani'],
    photoUrl: 'https://images.unsplash.com/photo-1583531172067-56ac79879f6a?w=600&h=400&fit=crop',
  },
  {
    id: 'd-galapagos',
    name: 'Galapagos Islands',
    country: 'Ecuador',
    region: 'South America',
    emoji: '',
    blurb: 'Walk among giant tortoises, sea lions, and blue-footed boobies — evolution\'s living laboratory.',
    bestMonths: 'Jun – Sep, Dec – Jan',
    dailyBudgetUsd: 200,
    tags: ['wildlife', 'nature', 'diving', 'adventure'],
    highlights: ['Giant Tortoises', 'Snorkeling with Sea Lions', 'Darwin Research Station', 'Isla Isabela'],
    photoUrl: 'https://images.unsplash.com/photo-1544979590-37e9b47eb705?w=600&h=400&fit=crop',
  },
  {
    id: 'd-lima',
    name: 'Lima',
    country: 'Peru',
    region: 'South America',
    emoji: '',
    blurb: 'The culinary capital of South America — ceviche, Pisco sours, and coastal charm.',
    bestMonths: 'Dec – Apr',
    dailyBudgetUsd: 55,
    tags: ['food', 'history', 'culture', 'budget'],
    highlights: ['Miraflores', 'Plaza de Armas', 'Barranco', 'Central Restaurant'],
    photoUrl: 'https://images.unsplash.com/photo-1531968455001-5c5272a67c71?w=600&h=400&fit=crop',
  },
  {
    id: 'd-patagonia',
    name: 'Patagonia',
    country: 'Argentina / Chile',
    region: 'South America',
    emoji: '',
    blurb: 'The end of the world — glaciers, jagged peaks, and vast windswept steppe.',
    bestMonths: 'Nov – Mar',
    dailyBudgetUsd: 120,
    tags: ['nature', 'hiking', 'adventure', 'photography'],
    highlights: ['Torres del Paine', 'Perito Moreno Glacier', 'Mount Fitz Roy', 'Ushuaia'],
    photoUrl: 'https://images.unsplash.com/photo-1531761535209-180857e67b72?w=600&h=400&fit=crop',
  },
  {
    id: 'd-marrakech',
    name: 'Marrakech',
    country: 'Morocco',
    region: 'Africa',
    emoji: '',
    blurb: 'A sensory overload of souks, spices, and riads in the heart of the Red City.',
    bestMonths: 'Mar – May, Sep – Nov',
    dailyBudgetUsd: 55,
    tags: ['culture', 'shopping', 'food', 'history'],
    highlights: ['Jemaa el-Fnaa', 'Majorelle Garden', 'Medina Souks', 'Atlas Mountains Day Trip'],
    photoUrl: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d23?w=600&h=400&fit=crop',
  },
  {
    id: 'd-victoria-falls',
    name: 'Victoria Falls',
    country: 'Zimbabwe / Zambia',
    region: 'Africa',
    emoji: '',
    blurb: 'The Smoke That Thunders — the world\'s largest sheet of falling water.',
    bestMonths: 'Feb – May',
    dailyBudgetUsd: 90,
    tags: ['nature', 'adventure', 'outdoors', 'photography'],
    highlights: ['Devil\'s Pool', 'Helicopter Flight', 'Bungee Jump', 'Zambezi Sunset Cruise'],
    photoUrl: 'https://images.unsplash.com/photo-1568219656418-15c329312bf1?w=600&h=400&fit=crop',
  },
  {
    id: 'd-zanzibar',
    name: 'Zanzibar',
    country: 'Tanzania',
    region: 'Africa',
    emoji: '',
    blurb: 'Spice island paradise — white-sand beaches, Stone Town alleys, and turquoise Indian Ocean.',
    bestMonths: 'Jun – Oct, Dec – Feb',
    dailyBudgetUsd: 60,
    tags: ['beach', 'culture', 'history', 'budget'],
    highlights: ['Stone Town', 'Nungwi Beach', 'Spice Tour', 'Prison Island'],
    photoUrl: 'https://images.unsplash.com/photo-1580741569354-b4e300dadd5a?w=600&h=400&fit=crop',
  },
  {
    id: 'd-queenstown',
    name: 'Queenstown',
    country: 'New Zealand',
    region: 'Oceania',
    emoji: '',
    blurb: 'The adventure capital of the world — bungee, skiing, and jaw-dropping mountain scenery.',
    bestMonths: 'Dec – Feb (summer), Jun – Aug (skiing)',
    dailyBudgetUsd: 140,
    tags: ['adventure', 'nature', 'outdoors', 'photography'],
    highlights: ['Bungee Jumping', 'Milford Sound', 'Skyline Gondola', 'Remarkables Ski Area'],
    photoUrl: 'https://images.unsplash.com/photo-1506197603052-3cc9c3a201bd?w=600&h=400&fit=crop',
  },
  {
    id: 'd-great-barrier-reef',
    name: 'Great Barrier Reef',
    country: 'Australia',
    region: 'Oceania',
    emoji: '',
    blurb: 'The world\'s largest coral reef system — snorkeling and diving in a technicolor underwater world.',
    bestMonths: 'Jun – Oct',
    dailyBudgetUsd: 150,
    tags: ['diving', 'nature', 'beach', 'adventure'],
    highlights: ['Snorkeling', 'Whitehaven Beach', 'Scenic Flights', 'Cairns Gateway'],
    photoUrl: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?w=600&h=400&fit=crop',
  },
  {
    id: 'd-bora-bora',
    name: 'Bora Bora',
    country: 'French Polynesia',
    region: 'Oceania',
    emoji: '',
    blurb: 'The ultimate island escape — overwater bungalows, volcanic peaks, and lagoon blues.',
    bestMonths: 'May – Oct',
    dailyBudgetUsd: 400,
    tags: ['luxury', 'romantic', 'beach', 'diving'],
    highlights: ['Overwater Bungalows', 'Mount Otemanu', 'Lagoon Tours', 'Shark & Ray Feeding'],
    photoUrl: 'https://images.unsplash.com/photo-1589197331516-4d84b72ebde3?w=600&h=400&fit=crop',
  },
  {
    id: 'd-fiji',
    name: 'Fiji',
    country: 'Fiji',
    region: 'Oceania',
    emoji: '',
    blurb: 'Over 300 tropical islands with warm hospitality, coral reefs, and swaying palm trees.',
    bestMonths: 'May – Oct',
    dailyBudgetUsd: 120,
    tags: ['beach', 'diving', 'nature', 'romantic'],
    highlights: ['Mamanuca Islands', 'Cloud 9 Floating Bar', 'Coral Reefs', 'Village Visits'],
    photoUrl: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=600&h=400&fit=crop',
  },
  {
    id: 'd-havana',
    name: 'Havana',
    country: 'Cuba',
    region: 'Caribbean',
    emoji: '',
    blurb: 'Vintage cars, salsa rhythms, and crumbling colonial grandeur frozen in time.',
    bestMonths: 'Nov – Apr',
    dailyBudgetUsd: 50,
    tags: ['culture', 'history', 'music', 'budget'],
    highlights: ['Old Havana', 'Malecon', 'Classic Car Tour', 'Tropicana Show'],
    photoUrl: 'https://images.unsplash.com/photo-1500759285222-a95626b934cb?w=600&h=400&fit=crop',
  },
  {
    id: 'd-st-lucia',
    name: 'St. Lucia',
    country: 'St. Lucia',
    region: 'Caribbean',
    emoji: '',
    blurb: 'Twin volcanic peaks, lush rainforest, and Caribbean beaches in a postcard-perfect island.',
    bestMonths: 'Dec – Apr',
    dailyBudgetUsd: 140,
    tags: ['beach', 'romantic', 'nature', 'adventure'],
    highlights: ['The Pitons', 'Sulphur Springs', 'Marigot Bay', 'Zip-lining'],
    photoUrl: 'https://images.unsplash.com/photo-1572099606223-6e29045d7de3?w=600&h=400&fit=crop',
  },
]

export const ALL_DESTINATIONS: Destination[] = [...DESTINATIONS, ...EXPLORE_EXTRA]
