const TRAVEL_TIMES: Record<string, { flight: string }> = {
  paris: { flight: '10h 30m' },
  france: { flight: '10h 30m' },
  tokyo: { flight: '13h 15m' },
  japan: { flight: '13h 15m' },
  kyoto: { flight: '14h' },
  osaka: { flight: '13h 45m' },
  london: { flight: '9h 30m' },
  'united kingdom': { flight: '9h 30m' },
  rome: { flight: '11h 45m' },
  italy: { flight: '11h 45m' },
  bali: { flight: '20h' },
  indonesia: { flight: '20h' },
  bangkok: { flight: '17h 30m' },
  thailand: { flight: '17h 30m' },
  sydney: { flight: '18h 30m' },
  australia: { flight: '18h 30m' },
  dubai: { flight: '15h 45m' },
  uae: { flight: '15h 45m' },
  'cape town': { flight: '20h' },
  'south africa': { flight: '20h' },
  reykjavik: { flight: '7h 30m' },
  iceland: { flight: '7h 30m' },
  'new york': { flight: '5h 15m' },
  nyc: { flight: '5h 15m' },
  'mexico city': { flight: '4h 30m' },
  mexico: { flight: '4h 30m' },
  cancun: { flight: '4h 45m' },
  barcelona: { flight: '11h' },
  spain: { flight: '11h' },
  amsterdam: { flight: '10h' },
  berlin: { flight: '10h 30m' },
  germany: { flight: '10h 30m' },
  singapore: { flight: '19h' },
  seoul: { flight: '13h' },
  korea: { flight: '13h' },
  hawaii: { flight: '5h 30m' },
  'los angeles': { flight: '1h 30m' },
  'san francisco': { flight: '1h 45m' },
  miami: { flight: '4h 45m' },
  cairo: { flight: '14h' },
  egypt: { flight: '14h' },
  istanbul: { flight: '13h' },
  turkey: { flight: '13h' },
  lisbon: { flight: '10h 45m' },
  portugal: { flight: '10h 45m' },
  'salt lake city': { flight: '1h 15m' },
  santorini: { flight: '13h' },
  greece: { flight: '12h 30m' },
  'grand canyon': { flight: '1h 45m' },
  arizona: { flight: '1h 45m' },
  banff: { flight: '3h 30m' },
  alberta: { flight: '3h 30m' },
  canada: { flight: '4h' },
  'chichen itza': { flight: '4h 45m' },
  'rio de janeiro': { flight: '12h 30m' },
  brazil: { flight: '12h 30m' },
  'machu picchu': { flight: '10h 30m' },
  peru: { flight: '10h 30m' },
  cusco: { flight: '10h 30m' },
  'great wall': { flight: '14h' },
  china: { flight: '14h' },
  beijing: { flight: '14h' },
  'mount fuji': { flight: '13h 30m' },
  'taj mahal': { flight: '18h' },
  agra: { flight: '18h' },
  india: { flight: '18h' },
  'ha long bay': { flight: '17h' },
  vietnam: { flight: '17h' },
  hanoi: { flight: '17h' },
  giza: { flight: '14h 30m' },
  'pyramids of giza': { flight: '14h 30m' },
  serengeti: { flight: '22h' },
  tanzania: { flight: '22h' },
  prague: { flight: '11h' },
  'czech republic': { flight: '11h' },
  vienna: { flight: '11h 30m' },
  austria: { flight: '11h 30m' },
  edinburgh: { flight: '10h' },
  scotland: { flight: '10h' },
  budapest: { flight: '11h 30m' },
  hungary: { flight: '11h 30m' },
  dubrovnik: { flight: '12h' },
  croatia: { flight: '12h' },
  florence: { flight: '11h 30m' },
  venice: { flight: '11h 45m' },
  copenhagen: { flight: '10h 30m' },
  denmark: { flight: '10h 30m' },
  'amalfi coast': { flight: '12h' },
  amalfi: { flight: '12h' },
  munich: { flight: '10h 45m' },
  'hong kong': { flight: '14h 30m' },
  maldives: { flight: '21h' },
  phuket: { flight: '18h 30m' },
  'angkor wat': { flight: '18h' },
  cambodia: { flight: '18h' },
  'siem reap': { flight: '18h' },
  kathmandu: { flight: '18h 30m' },
  nepal: { flight: '18h 30m' },
  jaipur: { flight: '18h 30m' },
  shanghai: { flight: '13h 30m' },
  petra: { flight: '14h 30m' },
  jordan: { flight: '14h 30m' },
  jerusalem: { flight: '14h' },
  israel: { flight: '14h' },
  'las vegas': { flight: '1h 30m' },
  honolulu: { flight: '5h 30m' },
  vancouver: { flight: '2h 30m' },
  'washington dc': { flight: '5h' },
  chicago: { flight: '4h' },
  'new orleans': { flight: '4h 15m' },
  yellowstone: { flight: '2h 30m' },
  'niagara falls': { flight: '5h 15m' },
  'buenos aires': { flight: '13h 30m' },
  argentina: { flight: '13h 30m' },
  cartagena: { flight: '7h 30m' },
  colombia: { flight: '7h 30m' },
  galapagos: { flight: '9h' },
  ecuador: { flight: '9h' },
  lima: { flight: '10h' },
  patagonia: { flight: '15h' },
  marrakech: { flight: '12h 30m' },
  morocco: { flight: '12h 30m' },
  'victoria falls': { flight: '22h' },
  zimbabwe: { flight: '22h' },
  zambia: { flight: '22h' },
  zanzibar: { flight: '22h' },
  queenstown: { flight: '17h' },
  'new zealand': { flight: '17h' },
  'great barrier reef': { flight: '18h' },
  cairns: { flight: '18h' },
  'bora bora': { flight: '9h 30m' },
  'french polynesia': { flight: '9h 30m' },
  fiji: { flight: '13h' },
  havana: { flight: '5h 30m' },
  cuba: { flight: '5h 30m' },
  'st lucia': { flight: '8h' },
  'saint lucia': { flight: '8h' },
}

export function lookupTime(destination: string): { flight: string } | null {
  if (!destination || destination.trim().length < 2) return null
  const lower = destination.toLowerCase()
  for (const [key, val] of Object.entries(TRAVEL_TIMES)) {
    if (lower.includes(key)) return val
  }
  return null
}

export function TravelTimeBanner({ destination }: { destination: string }) {
  const match = lookupTime(destination)
  if (!match) return null

  return (
    <div className="travel-time-bar">
      <span className="travel-time-icon">Flight</span>
      <span>
        Estimated travel time to{' '}
        <strong>{destination}</strong>: <strong>{match.flight}</strong> by air
      </span>
    </div>
  )
}
